using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CollegeAPI.Migrations
{
    /// <inheritdoc />
    public partial class RestoreStudentRecords : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Restore Student records that were cascade-deleted when seed data GUIDs
            // were regenerated by the RemoveDepartmentDescriptionFields migration.
            // Each INSERT is idempotent (guarded with NOT EXISTS).

            var branchSE = "ca4c3f51-4b60-4c1d-a34f-24921e81ee6e";
            var branchCS = "ae1e2c9d-88f9-4217-9c4a-c1abd479e88e";
            var branchIS = "768906fa-13c7-455c-8cdf-eeb9c43047cc";
            var branchAI = "3dd5318c-78f9-407b-ae02-2d17670740d2";
            var branchNE = "8d38e498-9a85-4be1-8a8d-4440402b918b";
            var branchMM = "e2d38afb-66e6-40db-a409-f687aa34ca87";

            var stagFirst = "de39baf0-b250-41ec-8ab0-115d0f57ae2a";
            var stagSecond = "363020b9-bbbb-4dff-957d-df338e47659d";
            var stagThird = "20540370-babc-48b3-bab2-23193d6694da";
            var stagFourth = "cd57c38a-77bd-4c9e-8dad-d9313744b924";

            var stMorning = "5593fee1-5208-4997-b82b-3600f29ab611";
            var stEvening = "85cf43fa-3d01-432f-9519-ac33ba6f4939";
            var stParallel = "e252fd78-871d-4b22-92ba-5672f72468b1";

            var students = new[]
            {
                ("ahmed.hassan@test.edu", "Male", branchSE, stMorning, stagFirst),
                ("fatima.ali@test.edu", "Female", branchSE, stEvening, stagSecond),
                ("mohammed.karim@test.edu", "Male", branchSE, stParallel, stagThird),
                ("zahra.mahmoud@test.edu", "Female", branchSE, stMorning, stagFourth),
                ("omar.saleh@test.edu", "Male", branchCS, stMorning, stagFirst),
                ("noor.ibrahim@test.edu", "Female", branchCS, stEvening, stagSecond),
                ("youssef.adel@test.edu", "Male", branchCS, stParallel, stagThird),
                ("maryam.khalil@test.edu", "Female", branchCS, stMorning, stagFourth),
                ("khalid.nasser@test.edu", "Male", branchIS, stMorning, stagFirst),
                ("layla.jamal@test.edu", "Female", branchIS, stEvening, stagSecond),
                ("tariq.faisal@test.edu", "Male", branchIS, stParallel, stagThird),
                ("amira.rashid@test.edu", "Female", branchIS, stMorning, stagFourth),
                ("samir.younis@test.edu", "Male", branchAI, stMorning, stagFirst),
                ("huda.mansour@test.edu", "Female", branchAI, stEvening, stagSecond),
                ("rami.zaki@test.edu", "Male", branchAI, stParallel, stagThird),
                ("sara.hamza@test.edu", "Female", branchAI, stMorning, stagFourth),
                ("bilal.mustafa@test.edu", "Male", branchNE, stMorning, stagFirst),
                ("rana.sami@test.edu", "Female", branchNE, stEvening, stagSecond),
                ("walid.tamer@test.edu", "Male", branchNE, stParallel, stagThird),
                ("dina.osama@test.edu", "Female", branchNE, stMorning, stagFourth),
                ("hani.majid@test.edu", "Male", branchMM, stMorning, stagFirst),
                ("lina.bashar@test.edu", "Female", branchMM, stEvening, stagSecond),
                ("adel.fouad@test.edu", "Male", branchMM, stParallel, stagThird),
                ("yasmin.hatem@test.edu", "Female", branchMM, stMorning, stagFourth),
            };

            foreach (var (email, gender, branch, studyType, stage) in students)
            {
                migrationBuilder.Sql($@"
                    INSERT INTO ""Students"" (""Id"", ""UserId"", ""Gender"", ""BranchId"", ""StudyTypeId"", ""StageId"")
                    SELECT gen_random_uuid(), u.""Id"", '{gender}', '{branch}'::uuid, '{studyType}'::uuid, '{stage}'::uuid
                    FROM ""Users"" u
                    WHERE u.""Email"" = '{email}'
                      AND NOT EXISTS (SELECT 1 FROM ""Students"" s WHERE s.""UserId"" = u.""Id"");
                ");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Down migration: remove the restored student records
            var emails = new[]
            {
                "ahmed.hassan@test.edu", "fatima.ali@test.edu", "mohammed.karim@test.edu", "zahra.mahmoud@test.edu",
                "omar.saleh@test.edu", "noor.ibrahim@test.edu", "youssef.adel@test.edu", "maryam.khalil@test.edu",
                "khalid.nasser@test.edu", "layla.jamal@test.edu", "tariq.faisal@test.edu", "amira.rashid@test.edu",
                "samir.younis@test.edu", "huda.mansour@test.edu", "rami.zaki@test.edu", "sara.hamza@test.edu",
                "bilal.mustafa@test.edu", "rana.sami@test.edu", "walid.tamer@test.edu", "dina.osama@test.edu",
                "hani.majid@test.edu", "lina.bashar@test.edu", "adel.fouad@test.edu", "yasmin.hatem@test.edu"
            };

            foreach (var email in emails)
            {
                migrationBuilder.Sql($@"
                    DELETE FROM ""Students""
                    WHERE ""UserId"" IN (SELECT ""Id"" FROM ""Users"" WHERE ""Email"" = '{email}');
                ");
            }
        }
    }
}
